# crear contenedor a partir de un archivo yaml
# sudo docker volume create postgres_data
# sudo docker-compose -f jenkins-localhost.yml up -d

volumes:
  jenkins_home:
    external: true
    
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts-jdk17
    ports:
      - "6060:8080"
      - "50000:50000"
    hostname: server_jenkins
    volumes:
      - jenkins_home:/var/jenkins_home
  ssh-agent:
    image: jenkins/ssh-agent


