# crear contenedor a partir de un archivo yaml
# sudo docker-compose -f mariadb-localhost.yml up -d
#### uso con Docker Desktop
# 

version: '3.9'
#Indica que red utlizar ojo con el nombre -- redlocal --

volumes:
  mariadb:    
    external: true 

services:
  mariadb:
    container_name: mariadb
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: MasterHunter*1972
      #MYSQL_DATABASE: mydatabase
      MYSQL_USER: lagaguate
      MYSQL_PASSWORD: MasterHunter*1972
    volumes:
      - mariadb:/var/lib/mysql
    ports:
      - "3306:3306"
    hostname: server_mariadb    