version: '3.1'
services:

  mongo:
    container_name: mongodb
    image: mongo
    restart: no
    volumes:
      - mongodb:/data/db
      - mongodb:/data/configdb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    hostname: servermongodb
      
  mongo-express:
    image: mongo-express
    restart: no
    
    depends_on:
      - mongo  
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/  
    ports:
      - 8084:8081  
    hostname: mongoexpress  
    