#docker-compose -f Ollama-Web.yml up -d
#http://localhost:3000
version: '3.8'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - ollama
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434/api
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  ollama_data:
  open-webui:


 #Para obtener la última versión, ejecuta:
# docker-compose pull open-webui && docker-compose up -d