# crear contenedor a partir de un archivo yaml
# docker-compose -f oracle-ords-localhost.yml up -d


version: '3'
services:
  ords:
    container_name: oracle-ords
    restart: no
    image: container-registry.oracle.com/database/ords:latest
           
    environment:
            admin-user: admin
            db-user: ORDS_PUBLIC_USER2
            gateway-user: ORDS_PLSQL_GATEWAY2 
            wallet: /opt/ords-config/Wallet_Autonomous.zip
            wallet-service-name: db202301101106_low
            feature-sdw: true 
            feature-db-api: true
            feature-rest-enabled-sql: true  
         
    volumes:
      - /home/lgutie/Dev/Containers/OracleSetting/ords_secrets/:/opt/oracle/variables/ 
      - /home/lgutie/Dev/Containers/OracleSetting/ords_config/:/etc/ords/config/
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
        - 8181:8181
    hostname: server_oracle_ords

# ingrese al contenedor
# sudo docker exec -i -t oracle-ords /bin/bash        

#
# CONN_STRING="sys as sysdba/MasterHunter@server_oracle_xe:1521/XEPDB1"

# http://localhost:8181/ords/apex 



