# crear volumen
# sudo docker volume create pgadmin
# crear contenedor a partir de un archivo yaml
# docker-compose -f pgadmin-localhost.yml up -d

# http://localhost:5050/login?next=%2F
version: "3.9"

# Indicar que el volumen es externo
volumes:
  pgadmin:    
    external: true          


services:
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    #restart: no
    ports:
      - "5050:80"
    hostname: server_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lagaguate@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin:/var/lib/pgadmin


