# crear volumen
# sudo docker volume create pgadmin
# crear contenedor a partir de un archivo yaml
# docker-compose -f pgadmin-localhost.yml up -d

# http://localhost:5050/login?next=%2F
#version: "3.9"

# Indicar que el volumen es externo
volumes:
  pgadmin4:    
    external: true          


services:
  pgadmin:
    image: dpage/pgadmin4:8.7
    container_name: pgadmin4
    #restart: no
    ports:
      - "5050:80"
    hostname: server_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: lagaguate@yahoo.com
      PGADMIN_DEFAULT_PASSWORD: admin
    volumes:
      - pgadmin4:/var/lib/pgadmin


# Configurar conexion en Pgadmin
# Paso 1. Server postgre, abrir propiedad
# paso 2. General, Name: server_postgres
# paso 3. Conexion, Host name / Address:  server_postgres
# paso 4. Conexion, port: 5432
# paso 5. Conexion, Mant.. Database: paciente
# paso 6. Conexion, user: paciente

