# Crear volumen 
# sudo docker volume create 
#

# crear contenedor a partir de un archivo yaml
# docker-compose -f mongodb.yml up -d
#### uso con Docker Desktop
# 

version: '3.9'
#Indica que red utlizar ojo con el nombre -- redlocal --
networks:
    redlocal:
        external: true

volumes:
  mongodb:    
    external: true 

services:
  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes:
      - mongodb:/data/db
    ports:
      - "27017:27017"
    networks:
      redlocal:
        ipv4_address: 10.72.0.9
    hostname: server_mongodb